### ISSUE TITLE
Failed on request of size 32800 in memory context "HashBatchContext".

### ISSUE THREAD

**Issue by palewire** [california-civic-data-coalition/django-calaccess-downloads-website#191]
```
2021-06-22T13:18:03.262346+00:00 app[clock.1]: django.db.utils.OperationalError: out of memory
2021-06-22T13:18:03.262346+00:00 app[clock.1]: DETAIL:  Failed on request of size 32800 in memory context "HashBatchContext".
```

**Comment by palewire** [comment]
Related

```
2021-07-01T13:14:14.084441+00:00 app[clock.1]: self.load_model_list(model_list)
2021-07-01T13:14:14.084442+00:00 app[clock.1]: File "/app/.heroku/python/lib/python3.9/site-packages/calaccess_processed_filings/management/commands/processcalaccessfilings.py", line 152, in load_model_list
2021-07-01T13:14:14.084443+00:00 app[clock.1]: m.objects.load()
2021-07-01T13:14:14.084443+00:00 app[clock.1]: File "/app/.heroku/python/lib/python3.9/site-packages/calaccess_processed_filings/managers.py", line 56, in load
2021-07-01T13:14:14.084443+00:00 app[clock.1]: c.execute(self.get_sql())
2021-07-01T13:14:14.084444+00:00 app[clock.1]: File "/app/.heroku/python/lib/python3.9/site-packages/django/db/backends/utils.py", line 98, in execute
2021-07-01T13:14:14.084444+00:00 app[clock.1]: return super().execute(sql, params)
2021-07-01T13:14:14.084445+00:00 app[clock.1]: File "/app/.heroku/python/lib/python3.9/site-packages/django/db/backends/utils.py", line 66, in execute
2021-07-01T13:14:14.084445+00:00 app[clock.1]: return self._execute_with_wrappers(sql, params, many=False, executor=self._execute)
2021-07-01T13:14:14.084445+00:00 app[clock.1]: File "/app/.heroku/python/lib/python3.9/site-packages/django/db/backends/utils.py", line 75, in _execute_with_wrappers
2021-07-01T13:14:14.084446+00:00 app[clock.1]: return executor(sql, params, many, context)
2021-07-01T13:14:14.084446+00:00 app[clock.1]: File "/app/.heroku/python/lib/python3.9/site-packages/django/db/backends/utils.py", line 84, in _execute
2021-07-01T13:14:14.084446+00:00 app[clock.1]: return self.cursor.execute(sql, params)
2021-07-01T13:14:14.084447+00:00 app[clock.1]: File "/app/.heroku/python/lib/python3.9/site-packages/django/db/utils.py", line 90, in __exit__
2021-07-01T13:14:14.084447+00:00 app[clock.1]: raise dj_exc_value.with_traceback(traceback) from exc_value
2021-07-01T13:14:14.084448+00:00 app[clock.1]: File "/app/.heroku/python/lib/python3.9/site-packages/django/db/backends/utils.py", line 82, in _execute
2021-07-01T13:14:14.084448+00:00 app[clock.1]: return self.cursor.execute(sql)
2021-07-01T13:14:14.084448+00:00 app[clock.1]: django.db.utils.OperationalError: out of memory
2021-07-01T13:14:14.084449+00:00 app[clock.1]: DETAIL:  Failed on request of size 6291456 in memory context "TupleSort main".
2021-07-01T13:14:14.084449+00:00 app[clock.1]: 
2021-07-01T15:00:00.674252+00:00 app[clock.1]: Your database is already up-to-date.
2021-07-01T15:00:00.675296+00:00 app[clock.1]: Job "updater (trigger: cron[hour='*/3', minute='0'], next run at: 2021-07-01 18:00:00 UTC)" raised an exception
2021-07-01T15:00:00.675297+00:00 app[clock.1]: Traceback (most recent call last):
2021-07-01T15:00:00.675298+00:00 app[clock.1]: File "/app/.heroku/python/lib/python3.9/site-packages/apscheduler/executors/base.py", line 125, in run_job
2021-07-01T15:00:00.675298+00:00 app[clock.1]: retval = job.func(*job.args, **job.kwargs)
2021-07-01T15:00:00.675298+00:00 app[clock.1]: File "/app/clock.py", line 21, in updater
2021-07-01T15:00:00.675300+00:00 app[clock.1]: call_command("updatedownloadswebsite", noinput=True, verbosity=3)
2021-07-01T15:00:00.675300+00:00 app[clock.1]: File "/app/.heroku/python/lib/python3.9/site-packages/django/core/management/__init__.py", line 181, in call_command
2021-07-01T15:00:00.675301+00:00 app[clock.1]: return command.execute(*args, **defaults)
2021-07-01T15:00:00.675301+00:00 app[clock.1]: File "/app/.heroku/python/lib/python3.9/site-packages/django/core/management/base.py", line 398, in execute
2021-07-01T15:00:00.675302+00:00 app[clock.1]: output = self.handle(*args, **options)
2021-07-01T15:00:00.675327+00:00 app[clock.1]: File "/app/calaccess_website/management/commands/updatedownloadswebsite.py", line 21, in handle
2021-07-01T15:00:00.675328+00:00 app[clock.1]: super(Command, self).handle(*args, **options)
2021-07-01T15:00:00.675329+00:00 app[clock.1]: File "/app/.heroku/python/lib/python3.9/site-packages/calaccess_raw/management/commands/updatecalaccessrawdata.py", line 135, in handle
2021-07-01T15:00:00.675330+00:00 app[clock.1]: exit(0)
2021-07-01T15:00:00.675331+00:00 app[clock.1]: SystemExit: 0
```
